sudo: false

language: dart

before_install:
  - nvm install node
  - node --version
script:
  - pub run test
  - pub build --mode=debug node_test
  - node build/node_test/platform_test.dart.js
  - node build/node_test/fs_test.dart.js
  - node build/node_test/promises_test.dart.js
  - node build/node_test/console_test.dart.js
