targets:
#  $default:
#    sources:
#      - "lib/**"
#      - "node/**"
  node_interop: # Replace this with your package name.
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - node/** # this doesn't work with dart2js
          - test/**_test.dart # this doesn't work with dart2js
#        options:
#          compiler: dart2js
#          node_preamble: true
#           List any dart2js specific args here, or omit it.
#          dart2js_args:
#          - --checked
