name: node_http
description: HTTP client powered by Node.js I/O.
version: 1.0.0-dev.2.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  http: ^0.11.3
  node_io: ^1.0.0-dev

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.7.9
  build_node_compilers: ^0.1.0
