name: node_io
description: Like dart:io but with Node.js.
version: 1.0.0-dev.8.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  node_interop: ^1.0.0-dev.2.0
  path: ^1.6.2

dev_dependencies:
  js: ^0.6.0
  test: ^1.0.0
  build_runner: ^0.10.0
  build_node_compilers: ^0.1.11
  build_test:
