name: node_interop
description: Node bindings and utils for Dart.
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^0.12.24
  build_runner: ^0.7.9
  build_node_compilers:
    git:
      url: https://github.com/pulyaevskiy/node-interop.git
      path: build_node_compilers
      ref: dart20
